version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      
  minio:
    image: minio/minio:RELEASE.2022-02-24T22-12-01Z.fips
    command: server --console-address :9001 /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: testkey
      MINIO_ROOT_PASSWORD: testsecret
    volumes:
      - minio-data:/data
  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.5.0.2:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

endpoints:
  - path: /
    service: db
    port: 3306

volumes:
  minio-data:
  my-db:
