version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      # HTTP
      - 8000:8181

    environment:

      NIFI_WEB_HTTP_PORT: 8181
      
    volumes:
      - ./nifi_state:/opt/nifi/nifi-current/state
      - ./nifi_db:/opt/nifi/nifi-current/database_repository
      - ./nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi_content:/opt/nifi/nifi-current/content_repository
      - ./nifi_provenance:/opt/nifi/nifi-current/provenance_repository
