version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      # HTTP
      - 8000:8181

    environment:

      NIFI_WEB_HTTP_PORT: 8181
      
    volumes:
      - nifi_data:/home/nifi

volumes:
  nifi_data:
    external: true
