version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    ports:
      # HTTP
      - 8000:8000

    environment:
      NIFI_WEB_HTTP_HOST: 0.0.0.0
      NIFI_WEB_HTTP_PORT: 8000
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: admin
      
    #volumes:
      #- nifi_data:/opt/nifi

#volumes:
 # nifi_data:
  #  external: true
