apiVersion: v1
kind: Service
metadata:
  labels:
    service: agent
  name: agent
spec:
spec:
  type: NodePort
  ports:
    - name: "28080"
      port: 28080
      targetPort: 28080
    - name: "9080"
      port: 9080
      targetPort: 9080
  selector:
    iservice: agent
status:
  loadBalancer: {}
