apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:

  #Credenciales de la base de datos
  DB_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
  
  #Consultas a realizar sobre la base de datos
  QUERY: SELECT data_before, data_after FROM items_updates WHERE time_stamp <= CURRENT_TIMESTAMP and processed = 0
  POST_QUERY: UPDATE items_updates set processed = 1, processed_timestamp = CURRENT_TIMESTAMP WHERE time_stamp <= CURRENT_TIMESTAMP and processed = 0
  
  #Carpetas de Minio
  MINIO_BUCKET: empleados
  MINIO_FOLDER: kubernetes_pruebas_carga
  MINIO_BUCKET_INVALID: empleados
  MINIO_FOLDER_INVALID: kubernetes_elementos_invalidos

   #Validaciones
  DEFAULT_SCHEMA: |-
        {
            "type": "record",
            "name": "NiFi_ExecuteSQL_Record",
            "namespace": "any.data",
            "fields": [
                {
                    "name": "DATA_BEFORE",
                    "type": ["null", 
                        {
                            "type": "record",
                            "name": "DATA_BEFORE",
                            "fields": [
                                {
                                    "name": "id",
                                    "type": "long"
                                }, 
                                {
                                    "name": "descripcion",
                                    "type": "string"
                                }, 
                                {
                                    "name": "uds",
                                    "type": "long"
                                }
                            ]
                        }
                    ]
                }, {
                    "name": "DATA_AFTER",
                    "type": ["null", 
                        {
                            "type": "record",
                            "name": "DATA_AFTER",
                            "fields": [
                                {
                                    "name": "id",
                                    "type": "long"
                                }, 
                                {
                                    "name": "descripcion",
                                    "type": "string"
                                }, 
                                {
                                    "name": "uds",
                                    "type": "long"
                                }
                            ]
                        }
                    ]
                }
            ]
        }  